app_user:
    resource: "@AppBundle/Resources/config/routing/user.php"
    prefix:   /secured/user

homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

secured:
    path: /secured
    defaults: { _controller: AppBundle:Secured:index }

login_route:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout